[versions]
groovy = "3.0.9"
spock = "2.0-groovy-3.0"

[libraries]
math = "org.apache.commons:commons-math3:3.6.1"
guava = "com.google.guava:guava:30.1.1-jre"
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }

[plugins]
spotbugs = "com.github.spotbugs:5.0.6"